# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssayIt < Formula
  desc "Confirm Quality and Eliminate Risk by Testing Microservices in Production."
  homepage "https://assay.it"
  version "1.0.6"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.6/assay-it_Darwin_arm64.tar.gz"
      sha256 "d4813bcefd56aa50f4d02c9c72704789a10cf2d5a6de3e989491498bf585b09f"

      def install
        bin.install "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.6/assay-it_Darwin_x86_64.tar.gz"
      sha256 "3cb0bdf0aa61c607c8b879a002ab352356369c38df36cc9afb6e969f2d1cf001"

      def install
        bin.install "assay-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.6/assay-it_Linux_arm64.tar.gz"
      sha256 "7f99a4f7f01e140f3eba1aa4ad01ebaa3dcb9aa36473071df61bfa67be6ff5e4"

      def install
        bin.install "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.6/assay-it_Linux_x86_64.tar.gz"
      sha256 "321fa0b17e84def49e74bfe8737b607db7e3735d50a9b1a02bc154afda26ec8d"

      def install
        bin.install "assay-it"
      end
    end
  end

  test do
    system "#{bin}/assay-it -v"
  end
end
