# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssayIt < Formula
  desc "Confirm Quality and Eliminate Risk by Testing Microservices in Production."
  homepage "https://assay.it"
  version "1.0.0"
  license "MIT"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.0/assay-it_Darwin_arm64.tar.gz"
      sha256 "d85cfcf07b5df7741143cb8bf031cb7297c017309e2519c297502fd74f49eeec"

      def install
        bin.install "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.0/assay-it_Darwin_x86_64.tar.gz"
      sha256 "08917074b9491d0e5aad3b44b9593a1d732f43cf11eeb8f75468d33769b6f295"

      def install
        bin.install "assay-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.0/assay-it_Linux_x86_64.tar.gz"
      sha256 "c2d89b71a7c3714374be954b1aa864576417306b32ca2d7fdd12bf5937a0605c"

      def install
        bin.install "assay-it"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assay-it/assay-it/releases/download/v1.0.0/assay-it_Linux_arm64.tar.gz"
      sha256 "592dc9a4947c6ed92dc94698ae94a1735893ddca037724bf4f01f1ad171f323d"

      def install
        bin.install "assay-it"
      end
    end
  end

  test do
    system "#{bin}/assay-it -v"
  end
end
